CREATE table if not exists rating(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar,
description varchar
);

CREATE table if not exists film(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar,
description varchar,
release date,
duration integer,
rating_id integer REFERENCES rating (id)
);

CREATE table if not exists "user"(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar,
login varchar,
name varchar,
birthday date
);

CREATE table if not exists genre(
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar
);

CREATE table if not exists film_genre(
film_id integer REFERENCES film(id),
genre_id integer REFERENCES genre(id)
);

CREATE table if not exists likes(
film_id integer REFERENCES film(id),
user_id integer REFERENCES "user"(id)
);

CREATE table if not exists user_friend(
user_id integer REFERENCES "user"(id),
friend_id integer REFERENCES "user"(id),
aproved boolean
);

